"""Initial migration

Revision ID: e89d6a10bbb6
Revises: 
Create Date: 2026-02-21 18:12:59.573187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e89d6a10bbb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('api_keys_key_hash_key', 'api_keys', type_='unique')
    op.drop_index('idx_api_keys_active', table_name='api_keys')
    op.drop_index('idx_api_keys_hash', table_name='api_keys')
    op.drop_index('idx_api_keys_org', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_is_active'), 'api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.drop_index('idx_organizations_email', table_name='organizations')
    op.drop_index('idx_organizations_tier', table_name='organizations')
    op.drop_constraint('organizations_email_key', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.create_index(op.f('ix_organizations_tier'), 'organizations', ['tier'], unique=False)
    op.alter_column('validation_logs', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('validation_logs', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('validation_logs', 'rules_applied',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('validation_logs', 'violations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_validation_logs_org', table_name='validation_logs')
    op.drop_index('idx_validation_logs_result', table_name='validation_logs')
    op.drop_index('idx_validation_logs_validation_id', table_name='validation_logs')
    op.drop_constraint('validation_logs_validation_id_key', 'validation_logs', type_='unique')
    op.create_index(op.f('ix_validation_logs_organization_id'), 'validation_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_validation_logs_result'), 'validation_logs', ['result'], unique=False)
    op.create_index(op.f('ix_validation_logs_validation_id'), 'validation_logs', ['validation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_logs_validation_id'), table_name='validation_logs')
    op.drop_index(op.f('ix_validation_logs_result'), table_name='validation_logs')
    op.drop_index(op.f('ix_validation_logs_organization_id'), table_name='validation_logs')
    op.create_unique_constraint('validation_logs_validation_id_key', 'validation_logs', ['validation_id'])
    op.create_index('idx_validation_logs_validation_id', 'validation_logs', ['validation_id'], unique=False)
    op.create_index('idx_validation_logs_result', 'validation_logs', ['result'], unique=False)
    op.create_index('idx_validation_logs_org', 'validation_logs', ['organization_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('validation_logs', 'violations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('validation_logs', 'rules_applied',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('validation_logs', 'output_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('validation_logs', 'input_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_tier'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.create_unique_constraint('organizations_email_key', 'organizations', ['email'])
    op.create_index('idx_organizations_tier', 'organizations', ['tier'], unique=False)
    op.create_index('idx_organizations_email', 'organizations', ['email'], unique=False)
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_active'), table_name='api_keys')
    op.create_index('idx_api_keys_org', 'api_keys', ['organization_id'], unique=False)
    op.create_index('idx_api_keys_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_active', 'api_keys', ['is_active'], unique=False)
    op.create_unique_constraint('api_keys_key_hash_key', 'api_keys', ['key_hash'])
    # ### end Alembic commands ###
